var dialog = {
  title: 'Enter Availability',
  callback_id: 'add_availability_dialog',
  submit_label: 'Submit',
  elements: [
    {
      label: 'Day',
      type: 'select',
      name: 'day1',
      options: [
        { label: 'Monday', value: 'Monday' },
        { label: 'Tuesday', value: 'Tuesday' },
        { label: 'Wednesday', value: 'Wednesday' },
        { label: 'Thursday', value: 'Thursday' },
        { label: 'Friday', value: 'Friday' },
        { label: 'Saturday', value: 'Saturday' },
        { label: 'Sunday', value: 'Sunday' },
      ],
    },
    {
      label: 'From Hour',
      type: 'select',
      name: 'from_time_hour',
      options: [
        { label: '07', value: '07' },
        { label: '08', value: '08' },
        { label: '09', value: '09' },
        { label: '10', value: '10' },
        { label: '11', value: '11' },
        { label: '12', value: '12' },
        { label: '13', value: '13' },
        { label: '14', value: '14' },
        { label: '15', value: '15' },
        { label: '16', value: '16' },
        { label: '17', value: '17' },
        { label: '18', value: '18' },
        { label: '19', value: '19' },
        { label: '20', value: '20' },
        { label: '21', value: '21' },
        { label: '22', value: '22' },
      ],
    },
    {
      label: 'From Min',
      type: 'select',
      name: 'from_time_min',
      options: [
        { label: '00', value: '00' },
        { label: '30', value: '30' },
      ],
    },
    {
      label: 'To Hour',
      type: 'select',
      name: 'to_time_hour',
      options: [
        { label: '07', value: '07' },
        { label: '08', value: '08' },
        { label: '09', value: '09' },
        { label: '10', value: '10' },
        { label: '11', value: '11' },
        { label: '12', value: '12' },
        { label: '13', value: '13' },
        { label: '14', value: '14' },
        { label: '15', value: '15' },
        { label: '16', value: '16' },
        { label: '17', value: '17' },
        { label: '18', value: '18' },
        { label: '19', value: '19' },
        { label: '20', value: '20' },
        { label: '21', value: '21' },
        { label: '22', value: '22' },
      ],
    },
    {
      label: 'To Min',
      type: 'select',
      name: 'to_time_min',
      options: [
        { label: '00', value: '00' },
        { label: '30', value: '30' },
      ],
    },
  ],
}

module.exports= {add_availability_dialog: dialog};
